// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

//Firebase 설정 정보 관리
//플랫폼별 Firebase 구성 제공

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMLr7jyMbuzqrvwJMHNjOCvzUMlYS2VDo',
    appId: '1:700373659727:web:ae0c980ebc237a9d6b3a3a',
    messagingSenderId: '700373659727',
    projectId: 'flutterproject3-af322',
    authDomain: 'flutterproject3-af322.firebaseapp.com',
    storageBucket: 'flutterproject3-af322.firebasestorage.app',
    measurementId: 'G-QPLLZNWFK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqhAqrQxkFvAk7WQDpm9pIi6MutTO0c5w',
    appId: '1:700373659727:android:325f7e22755aeef96b3a3a',
    messagingSenderId: '700373659727',
    projectId: 'flutterproject3-af322',
    storageBucket: 'flutterproject3-af322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbWHCInECdS8bMwfxLcmznLanX6jegZA',
    appId: '1:700373659727:ios:3ea33008ee326e906b3a3a',
    messagingSenderId: '700373659727',
    projectId: 'flutterproject3-af322',
    storageBucket: 'flutterproject3-af322.firebasestorage.app',
    androidClientId: '700373659727-jlq5hvo6s7e6r1me4joh9ocj7skm9k1b.apps.googleusercontent.com',
    iosClientId: '700373659727-t3t89luvegusfl5cfeogsuf55go3uqmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPractice3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvbWHCInECdS8bMwfxLcmznLanX6jegZA',
    appId: '1:700373659727:ios:3ea33008ee326e906b3a3a',
    messagingSenderId: '700373659727',
    projectId: 'flutterproject3-af322',
    storageBucket: 'flutterproject3-af322.firebasestorage.app',
    androidClientId: '700373659727-jlq5hvo6s7e6r1me4joh9ocj7skm9k1b.apps.googleusercontent.com',
    iosClientId: '700373659727-t3t89luvegusfl5cfeogsuf55go3uqmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPractice3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMLr7jyMbuzqrvwJMHNjOCvzUMlYS2VDo',
    appId: '1:700373659727:web:375f2e403af7a6a76b3a3a',
    messagingSenderId: '700373659727',
    projectId: 'flutterproject3-af322',
    authDomain: 'flutterproject3-af322.firebaseapp.com',
    storageBucket: 'flutterproject3-af322.firebasestorage.app',
    measurementId: 'G-2XVH1Q0T2E',
  );

}